# Generated by Django 5.0.3 on 2024-05-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateField(auto_now_add=True)),
                ('devolucaoPrevista', models.DateField()),
                ('dataDevolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('R', 'RECUSADO'), ('C', 'CANCELADO')], default='P', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('nota', models.IntegerField(blank=True, default=0, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('autor', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('editora', models.CharField(max_length=30)),
                ('idade', models.CharField(choices=[('L', 'LIVRE'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=35)),
                ('dataLancamento', models.DateField(auto_now_add=True)),
                ('publicacao', models.DateField()),
                ('categoria', models.CharField(choices=[('T', 'TERROR'), ('R', 'ROMANCE'), ('A', 'AVENTURA'), ('M', 'MISTÉRIO'), ('FC', 'FICÇÃO CIENTÍFICA'), ('D', 'DRAMA'), ('C', 'CRIME'), ('H', 'HISTÓRIA'), ('B', 'BIOGRAFIA'), ('E', 'ENSINO'), ('P', 'POESIA'), ('AA', 'AUTOAJUDA'), ('F', 'FANTASIA'), ('LIJ', 'LITERATURA INFANTO-JUVENIL')], max_length=30)),
                ('fotoFK', models.CharField(max_length=3000)),
                ('numeroPaginas', models.IntegerField()),
                ('formato', models.CharField(choices=[('E', 'EBOOK'), ('F', 'FÍSICO')], max_length=30)),
                ('codEdicao', models.CharField(max_length=25)),
                ('aprovado', models.CharField(choices=[('P', 'PENDENTE'), ('C', 'CANCELADO'), ('A', 'APROVADO')], default='P', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EmprestimoLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('emprestimoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_Emprestimo0', to='emprestimo.emprestimo')),
                ('livroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emprestimo_livr0o', to='emprestimo.livros')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_customizado_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_customizado_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuarioFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEmprestimo0', to='emprestimo.usuariocustomizado'),
        ),
    ]
